modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT"

[[mods]]
modId = "i18nupdatemod"
version = "${version}"
displayName = "I18nUpdateMod Non-LTS"
logoFile="icon.png"
credits="TartaricAcid, baka-gourd, exzhawk"
authors="TexTrue"
description='''
自动汉化更新模组
'''

[[dependencies.i18nupdatemod]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.i18nupdatemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.i18nupdatemod]]
modId = "cloth_config"
mandatory = true
versionRange = "[6,)"
ordering = "NONE"
side = "BOTH"