name: Gradle Build

on: [ pull_request, push ]

jobs:
  forge-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build with Gradle
        run: |
          cd ${{ github.workspace }}/forge
          chmod +x gradlew
          sh ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Forge-Artifacts
          path: build/libs

  fabric-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build with Gradle
        run: |
          cd ${{ github.workspace }}/fabric
          chmod +x gradlew
          sh ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
         name: Fabric-Artifacts
         path: build/libs